# ==========================================
# BANCO DE DADOS
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/bombeiros
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# ==========================================
# JPA / HIBERNATE
# ==========================================
# Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
# Mostra SQL no terminal
spring.jpa.show-sql=true
# Formata o SQL exibido
spring.jpa.properties.hibernate.format_sql=true